### Introduction to Machine Learning
#### 主題：numpy 的基本矩陣運算
##### prepared by Chao-Lin Liu

In [1]:
import numpy as np

In [2]:
x1d = np.array([1,2,3])
y1d = np.array([4,5,6])

In [3]:
xy1d = x1d * y1d
yx1d = y1d * x1d

In [4]:
xy1d

array([ 4, 10, 18])

In [5]:
yx1d

array([ 4, 10, 18])

$x2d = \begin{bmatrix}1 & 2\\3 & 4\end{bmatrix}$
$y2d = \begin{bmatrix}5 & 6\\7 & 8\end{bmatrix}$

In [6]:
x2d = np.array([[1,2],[3,4]])
y2d = np.array([[5,6],[7,8]])

In [7]:
xy2d = x2d*y2d
yx2d = y2d*x2d
xy2dmat = np.dot(x2d, y2d)
yx2dmat = np.dot(y2d, x2d)

In [8]:
xy2d

array([[ 5, 12],
       [21, 32]])

In [9]:
yx2d

array([[ 5, 12],
       [21, 32]])

In [10]:
xy2dmat

array([[19, 22],
       [43, 50]])

In [11]:
yx2dmat

array([[23, 34],
       [31, 46]])

$m1 = \begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\end{bmatrix}$
$m2 = \begin{bmatrix}1 & 2\\3 & 4\\5  & 6\end{bmatrix}$

In [12]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,2],[3,4],[5,6]])

In [13]:
#m1m2 = m1*m2  # 錯誤指令

In [14]:
#m2m1 = m2*m1  # 錯誤指令

In [15]:
m1m2mat = np.dot(m1,m2)

In [16]:
m1m2mat

array([[22, 28],
       [49, 64]])

In [17]:
m2m1mat = np.dot(m2,m1)

In [18]:
m2m1mat

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])