### Introduction to Machine Learning
##### https://scikit-learn.org/stable/modules/neural_networks_supervised.html
##### https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html
#### prepared by Chao-Lin Liu

###### 如果你直接執行這一個程式的話，會看到很低的辨識率，甚至看到一些警訊。嘗試改變一下 MLPClassifier 的參數設定，解決那一些問題。 你應該可以達成˙ $F_1$ 76%以上的辨識率

In [14]:
import pandas as pd
import numpy as np
df = pd.read_csv("introML2019.taskx.train.csv")

In [15]:
df[0:5]

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0    3.03072    3.82764    0.58316    0.05098    2.33048    1.31349   
1    2.06554    2.58245    2.78158    2.64259    0.36718    0.72675   
2    4.79113    4.26817    3.31938    1.69178    0.60181    0.97848   
3    0.54282    0.70391    4.64737    2.79710    1.97160    0.72203   
4    3.03771    2.79512    1.23405    0.43138    0.71433    0.77471   

   feature_6  feature_7  feature_8  feature_9  feature_10  feature_11  \
0    0.83424    3.03314    0.94328    1.23016     0.24975     0.85205   
1    5.03764    2.74495    0.23774    0.50992     0.52516     0.08850   
2    2.77091    0.64957    0.15596    0.81251     0.47414     1.27370   
3    4.49158    0.01500    0.91521    0.93423     0.31449     0.01357   
4    3.04295    1.22548    3.13544    0.38265     0.33434     1.14438   

   feature_12  feature_13  label  
0     0.34522     1.33981      0  
1     0.16748     1.71180      0  
2     1.66604     1.27203      0  
3     0.78556     1.27886      0  
4     0.99043     1.28083      0

In [16]:
X_train = np.array(df.iloc[:,0:14])
y_train = np.array(df.iloc[:,14:15]).reshape(-1)

In [17]:
X_train[0:3]

array([[3.03072, 3.82764, 0.58316, 0.05098, 2.33048, 1.31349, 0.83424,
        3.03314, 0.94328, 1.23016, 0.24975, 0.85205, 0.34522, 1.33981],
       [2.06554, 2.58245, 2.78158, 2.64259, 0.36718, 0.72675, 5.03764,
        2.74495, 0.23774, 0.50992, 0.52516, 0.0885 , 0.16748, 1.7118 ],
       [4.79113, 4.26817, 3.31938, 1.69178, 0.60181, 0.97848, 2.77091,
        0.64957, 0.15596, 0.81251, 0.47414, 1.2737 , 1.66604, 1.27203]])

In [18]:
y_train[30663:30666]

array([3, 3, 3])

In [19]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, learning_rate='adaptive', max_iter=20, hidden_layer_sizes=(10, 2), random_state=1)
clf.fit(X_train, y_train)  

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 2), learning_rate='adaptive',
       learning_rate_init=0.001, max_iter=20, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [20]:
df2 = pd.read_csv("introML2019.taskx.test.csv")

In [21]:
testX = np.array(df2.iloc[:,0:14])

In [22]:
testy = np.array(df2.iloc[:,14:15]).reshape(-1)

In [23]:
predicty = clf.predict(testX)

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(testy,predicty))

#可以參考 https://blog.csdn.net/m0_38061927/article/details/77198990

[[   0    0  162  104 2234]
 [   0    0  230  141 2129]
 [   0    0  213  358 1929]
 [   0    0  176  875 1449]
 [   0    0  110   50 2340]]


In [25]:
print(classification_report(testy,predicty))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      2500
           1       0.00      0.00      0.00      2500
           2       0.24      0.09      0.13      2500
           3       0.57      0.35      0.43      2500
           4       0.23      0.94      0.37      2500

   micro avg       0.27      0.27      0.27     12500
   macro avg       0.21      0.27      0.19     12500
weighted avg       0.21      0.27      0.19     12500



/home/tom/anaconda3/envs/testJ/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [30]:
clf = MLPClassifier(solver='adam', alpha=1e-5, learning_rate='adaptive', max_iter=20, hidden_layer_sizes=(14, 14, 14, 14, 1), random_state=1)
clf.fit(X_train, y_train)  

predicty = clf.predict(testX)

print(confusion_matrix(testy,predicty))
print(classification_report(testy,predicty))

[[2084    1   78    6  331]
 [   0 2463    4   33    0]
 [   3   24 2321   62   90]
 [   0  446  133 1918    3]
 [ 195    4  231   14 2056]]
              precision    recall  f1-score   support

           0       0.91      0.83      0.87      2500
           1       0.84      0.99      0.91      2500
           2       0.84      0.93      0.88      2500
           3       0.94      0.77      0.85      2500
           4       0.83      0.82      0.83      2500

   micro avg       0.87      0.87      0.87     12500
   macro avg       0.87      0.87      0.87     12500
weighted avg       0.87      0.87      0.87     12500



/home/tom/anaconda3/envs/testJ/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [35]:
clf = MLPClassifier(solver='adam', alpha=1e-5, learning_rate='adaptive', max_iter=200, hidden_layer_sizes=(14, 14, 14, 14, 1), random_state=1)
clf.fit(X_train, y_train)  

predicty = clf.predict(testX)

print(confusion_matrix(testy,predicty))
print(classification_report(testy,predicty))

[[2251    0   48    4  197]
 [   0 2491    0    9    0]
 [   0    1 2398   48   53]
 [   0   15   43 2442    0]
 [   6    1   30   11 2452]]
              precision    recall  f1-score   support

           0       1.00      0.90      0.95      2500
           1       0.99      1.00      0.99      2500
           2       0.95      0.96      0.96      2500
           3       0.97      0.98      0.97      2500
           4       0.91      0.98      0.94      2500

   micro avg       0.96      0.96      0.96     12500
   macro avg       0.96      0.96      0.96     12500
weighted avg       0.96      0.96      0.96     12500



In [37]:
clf = MLPClassifier(solver='adam', alpha=1e-5, learning_rate='adaptive', max_iter=200, hidden_layer_sizes=(14, 14, 14, 14, 14), random_state=1)
clf.fit(X_train, y_train)  

predicty = clf.predict(testX)

print(confusion_matrix(testy,predicty))
print(classification_report(testy,predicty))

[[2299    0   67   11  123]
 [   0 2496    1    3    0]
 [  10    4 2426   27   33]
 [   2   17   12 2468    1]
 [  39    0    9   10 2442]]
              precision    recall  f1-score   support

           0       0.98      0.92      0.95      2500
           1       0.99      1.00      1.00      2500
           2       0.96      0.97      0.97      2500
           3       0.98      0.99      0.98      2500
           4       0.94      0.98      0.96      2500

   micro avg       0.97      0.97      0.97     12500
   macro avg       0.97      0.97      0.97     12500
weighted avg       0.97      0.97      0.97     12500



In [34]:
clf = MLPClassifier(solver='adam', alpha=1e-5, learning_rate='adaptive', max_iter=20, hidden_layer_sizes=(16, 16, 16, 16, 16), random_state=1)
clf.fit(X_train, y_train)  

predicty = clf.predict(testX)

print(confusion_matrix(testy,predicty))
print(classification_report(testy,predicty))

[[2227    0   50   12  211]
 [   0 2497    3    0    0]
 [  19    3 2339   85   54]
 [   6   20   50 2423    1]
 [  73    1   58   21 2347]]
              precision    recall  f1-score   support

           0       0.96      0.89      0.92      2500
           1       0.99      1.00      0.99      2500
           2       0.94      0.94      0.94      2500
           3       0.95      0.97      0.96      2500
           4       0.90      0.94      0.92      2500

   micro avg       0.95      0.95      0.95     12500
   macro avg       0.95      0.95      0.95     12500
weighted avg       0.95      0.95      0.95     12500



/home/tom/anaconda3/envs/testJ/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [36]:
clf = MLPClassifier(solver='adam', alpha=1e-5, learning_rate='adaptive', max_iter=200, hidden_layer_sizes=(16, 16, 16, 16, 16), random_state=1)
clf.fit(X_train, y_train)  

predicty = clf.predict(testX)

print(confusion_matrix(testy,predicty))
print(classification_report(testy,predicty))

[[2361    0   37    5   97]
 [   0 2499    0    1    0]
 [   4    1 2462   22   11]
 [   1   10   12 2475    2]
 [  20    0   10    6 2464]]
              precision    recall  f1-score   support

           0       0.99      0.94      0.97      2500
           1       1.00      1.00      1.00      2500
           2       0.98      0.98      0.98      2500
           3       0.99      0.99      0.99      2500
           4       0.96      0.99      0.97      2500

   micro avg       0.98      0.98      0.98     12500
   macro avg       0.98      0.98      0.98     12500
weighted avg       0.98      0.98      0.98     12500

