### Introduction to Machine Learning
##### https://keras.io/getting-started/sequential-model-guide/
#### prepared by Chao-Lin Liu
###### 目前這一個程式的辨識率很差
###### 改變一下你的 sequential model 的設定，看看能不能達成比較高的辨識率？
###### 能不能把辨識率提高到 90% 以上？

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("introML2019.taskx.train.csv")

In [3]:
df[0:5]

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0    3.03072    3.82764    0.58316    0.05098    2.33048    1.31349   
1    2.06554    2.58245    2.78158    2.64259    0.36718    0.72675   
2    4.79113    4.26817    3.31938    1.69178    0.60181    0.97848   
3    0.54282    0.70391    4.64737    2.79710    1.97160    0.72203   
4    3.03771    2.79512    1.23405    0.43138    0.71433    0.77471   

   feature_6  feature_7  feature_8  feature_9  feature_10  feature_11  \
0    0.83424    3.03314    0.94328    1.23016     0.24975     0.85205   
1    5.03764    2.74495    0.23774    0.50992     0.52516     0.08850   
2    2.77091    0.64957    0.15596    0.81251     0.47414     1.27370   
3    4.49158    0.01500    0.91521    0.93423     0.31449     0.01357   
4    3.04295    1.22548    3.13544    0.38265     0.33434     1.14438   

   feature_12  feature_13  label  
0     0.34522     1.33981      0  
1     0.16748     1.71180      0  
2     1.66604     1.27203      0  
3     0.78556     1.27886      0  
4     0.99043     1.28083      0

In [4]:
X_train = np.array(df.iloc[:,0:14])
y_train = np.array(df.iloc[:,14:15]).reshape(-1)

In [5]:
#shuffle data
from sklearn.utils import shuffle
X_train, y_train = shuffle(X_train, y_train, random_state=119)

In [6]:
# 以下的步驟在 Introduction to Machine learning 課程並沒有講到
# 我們把 y 的數值變成了向量 － one-hot vector
#
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(y_train)
encoded_npy = encoder.transform(y_train)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_npy = np_utils.to_categorical(encoded_npy)

Using TensorFlow backend.


In [7]:
# 你可以試著增加 Dense 層的數目、或者改變個別 Dense 層的 nodes 數目、或者改變 activation functions
#
from keras.models import Sequential
from keras.layers import Dense, Dropout
# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(9, input_dim=14, activation='sigmoid'))
    model.add(Dense(9, activation='relu'))
    model.add(Dense(5, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [8]:
model2 = baseline_model()

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
# 在這裡，你可以嘗試增減 epochs 和 batch_size
model2.fit(X_train , dummy_npy, epochs=20, batch_size=5000, verbose=1, shuffle=True)

Instructions for updating:
Use tf.cast instead.
Epoch 1/20
50000/50000 [==============================] - 1s 25us/step - loss: 1.6585 - acc: 0.1583
Epoch 2/20
50000/50000 [==============================] - 0s 3us/step - loss: 1.6327 - acc: 0.1689
Epoch 3/20
50000/50000 [==============================] - 0s 3us/step - loss: 1.6154 - acc: 0.2171
Epoch 4/20
50000/50000 [==============================] - 0s 3us/step - loss: 1.6042 - acc: 0.2506
Epoch 5/20
50000/50000 [==============================] - 0s 3us/step - loss: 1.5959 - acc: 0.2580
Epoch 6/20
50000/50000 [==============================] - 0s 3us/step - loss: 1.5880 - acc: 0.2653
Epoch 7/20
50000/50000 [==============================] - 0s 3us/step - loss: 1.5793 - acc: 0.2758
Epoch 8/20
50000/50000 [==============================] - 0s 3us/step - loss: 1.5686 - acc: 0.2944
Epoch 9/20
50000/50000 [==============================] - 0s 3us/step - loss: 1.5557 - acc: 0.3196
Epoch 10/20
50000/50000 [==============================] - 0

In [10]:
df2 = pd.read_csv("introML2019.taskx.test.csv")

In [11]:
testX = np.array(df2.iloc[:,0:14])

In [12]:
predicty = model2.predict(testX)

In [13]:
predicty[0:5]

array([[0.25848746, 0.20733264, 0.14432363, 0.1686158 , 0.22124049],
       [0.23681776, 0.16600558, 0.18886667, 0.2138419 , 0.19446817],
       [0.34597865, 0.18853168, 0.12200107, 0.11698179, 0.22650689],
       [0.23070575, 0.1767936 , 0.17071044, 0.22797617, 0.19381398],
       [0.17329623, 0.16133949, 0.28532833, 0.25694138, 0.12309461]],
      dtype=float32)

In [14]:
testy = np.array(df2.iloc[:,14:15]).reshape(-1)

In [15]:
predicty = encoder.inverse_transform([np.argmax(item) for item in predicty])

In [16]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(testy,predicty))

[[1501   18  201  160  620]
 [ 679  230  375 1007  209]
 [  97   16 1918  446   23]
 [ 384   41  681 1033  361]
 [ 685   23  113  187 1492]]


In [17]:
print(classification_report(testy,predicty))

              precision    recall  f1-score   support

           0       0.45      0.60      0.51      2500
           1       0.70      0.09      0.16      2500
           2       0.58      0.77      0.66      2500
           3       0.36      0.41      0.39      2500
           4       0.55      0.60      0.57      2500

   micro avg       0.49      0.49      0.49     12500
   macro avg       0.53      0.49      0.46     12500
weighted avg       0.53      0.49      0.46     12500



In [30]:
model = Sequential()
model.add(Dense(16, input_dim=14, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(16, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(5, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# 在這裡，你可以嘗試增減 epochs 和 batch_size
#model.fit(X_train , dummy_npy, epochs=200, batch_size=5000, verbose=1, shuffle=True)
model.fit(X_train, dummy_npy,
          batch_size=200,
          epochs=200,
          verbose=1,
          shuffle=True)

predicty = model.predict(testX)
predicty = encoder.inverse_transform([np.argmax(item) for item in predicty])
print(confusion_matrix(testy,predicty))
print(classification_report(testy,predicty))

Epoch 1/200
50000/50000 [==============================] - 6s 114us/step - loss: 1.5633 - acc: 0.2734
Epoch 2/200
50000/50000 [==============================] - 2s 37us/step - loss: 1.2305 - acc: 0.4679
Epoch 3/200
50000/50000 [==============================] - 2s 36us/step - loss: 1.0563 - acc: 0.5398
Epoch 4/200
50000/50000 [==============================] - 2s 37us/step - loss: 0.9720 - acc: 0.5710
Epoch 5/200
50000/50000 [==============================] - 2s 37us/step - loss: 0.9212 - acc: 0.5919
Epoch 6/200
50000/50000 [==============================] - 2s 37us/step - loss: 0.8816 - acc: 0.6081
Epoch 7/200
50000/50000 [==============================] - 2s 37us/step - loss: 0.8502 - acc: 0.6232
Epoch 8/200
50000/50000 [==============================] - 2s 36us/step - loss: 0.8278 - acc: 0.6349
Epoch 9/200
50000/50000 [==============================] - 2s 36us/step - loss: 0.8044 - acc: 0.6499
Epoch 10/200
50000/50000 [==============================] - 2s 35us/step - loss: 0.7862 - 

50000/50000 [==============================] - 2s 34us/step - loss: 0.4938 - acc: 0.8348
Epoch 131/200
50000/50000 [==============================] - 2s 33us/step - loss: 0.4938 - acc: 0.8324
Epoch 132/200
50000/50000 [==============================] - 2s 37us/step - loss: 0.4965 - acc: 0.8325
Epoch 133/200
50000/50000 [==============================] - 2s 36us/step - loss: 0.5049 - acc: 0.8286
Epoch 134/200
50000/50000 [==============================] - 2s 35us/step - loss: 0.4950 - acc: 0.8331
Epoch 135/200
50000/50000 [==============================] - 2s 35us/step - loss: 0.4884 - acc: 0.8348
Epoch 136/200
50000/50000 [==============================] - 2s 34us/step - loss: 0.4868 - acc: 0.8355
Epoch 137/200
50000/50000 [==============================] - 2s 36us/step - loss: 0.4957 - acc: 0.8330
Epoch 138/200
50000/50000 [==============================] - 2s 36us/step - loss: 0.4963 - acc: 0.8319
Epoch 139/200
50000/50000 [==============================] - 2s 36us/step - loss: 0.486

In [31]:
# dropout 使用的限制 https://stats.stackexchange.com/questions/299292/dropout-makes-performance-worse
model = Sequential()
model.add(Dense(16, input_dim=14, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(5, activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# 在這裡，你可以嘗試增減 epochs 和 batch_size
#model.fit(X_train , dummy_npy, epochs=200, batch_size=5000, verbose=1, shuffle=True)
model.fit(X_train, dummy_npy,
          batch_size=200,
          epochs=200,
          verbose=1,
          shuffle=True)

predicty = model.predict(testX)
predicty = encoder.inverse_transform([np.argmax(item) for item in predicty])
print(confusion_matrix(testy,predicty))
print(classification_report(testy,predicty))

Epoch 1/200
50000/50000 [==============================] - 3s 62us/step - loss: 0.9574 - acc: 0.5846
Epoch 2/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.4860 - acc: 0.8078
Epoch 3/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.3692 - acc: 0.8544
Epoch 4/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.3062 - acc: 0.8854
Epoch 5/200
50000/50000 [==============================] - 1s 29us/step - loss: 0.2752 - acc: 0.9007
Epoch 6/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.2546 - acc: 0.9116
Epoch 7/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.2407 - acc: 0.9180
Epoch 8/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.2339 - acc: 0.9204
Epoch 9/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.2257 - acc: 0.9249
Epoch 10/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.2219 - a

50000/50000 [==============================] - 1s 28us/step - loss: 0.1000 - acc: 0.9683
Epoch 82/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0970 - acc: 0.9696
Epoch 83/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0993 - acc: 0.9685
Epoch 84/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0979 - acc: 0.9692
Epoch 85/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0952 - acc: 0.9701
Epoch 86/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0950 - acc: 0.9703
Epoch 87/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0964 - acc: 0.9699
Epoch 88/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0944 - acc: 0.9705
Epoch 89/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0958 - acc: 0.9697
Epoch 90/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.0948 - acc: 

50000/50000 [==============================] - 1s 27us/step - loss: 0.0661 - acc: 0.9787
Epoch 161/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.0630 - acc: 0.9800
Epoch 162/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.0657 - acc: 0.9792
Epoch 163/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.0657 - acc: 0.9794
Epoch 164/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.0636 - acc: 0.9794
Epoch 165/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.0634 - acc: 0.9797
Epoch 166/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.0637 - acc: 0.9794
Epoch 167/200
50000/50000 [==============================] - 1s 27us/step - loss: 0.0631 - acc: 0.9799
Epoch 168/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.0631 - acc: 0.9798
Epoch 169/200
50000/50000 [==============================] - 1s 28us/step - loss: 0.061